"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { useRouter, useSearchParams } from "next/navigation";
import { AlertTriangle, ArrowDownToLine, ArrowLeft, ArrowRight, BookOpen, ClipboardList, FileText, LayoutDashboard, Loader2, RefreshCw, Search, Shield, Star, Users, Wrench, X } from "lucide-react";
import type { Capabilities, AdminView, FeatureStatus } from "@/lib/admin-workspace";

type Business={id?:string;trading_name:string;slug?:string|null;area?:string};
type Row={id:string;trading_name?:string;business?:string;slug?:string|null;area?:string;profile_id?:string|null;pirb_number?:string|null;is_verified?:boolean;is_certified?:boolean;verification_state?:string;verification_source_url?:string;credential_verified_at?:string;verification_expires_at?:string;record_status?:string;whatsapp_number?:string;specialties?:string[];created_at:string;updated_at?:string;email?:string;full_name?:string;role?:string;reviewer_name?:string;rating?:number;comment?:string|null;history_state?:string;customer_name?:string;customer_phone?:string;job_description?:string;preferred_datetime?:string;status?:string;notes?:string;admin_notes?:string;phone_entered?:string;plumber_id?:string;claimant_id?:string;plumber?:Business|Business[];claimant?:{full_name?:string;email?:string};certifications?:Array<{count:number}>;photos?:Array<{count:number}>};
type Metric={value:number|null;status:FeatureStatus};
type Probe={table:string;visibleRows:number|null;totalRows:number|null;status:string;message:string};
type Data={items?:Row[];total?:number;page?:number;pageSize?:number;capabilities?:Capabilities;counts?:{current:number;history:number;total:number;duplicateGroups:number};complete?:boolean;notice?:string;published?:Metric;pending?:Metric;claims?:Metric;users?:Metric;bookings?:Metric;reviews?:Metric;contacts30d?:number|null;probes?:Probe[];certBucket?:string;checkedAt?:string;policySql?:string;limitations?:string[]};
type Detail={plumber?:Row;certifications?:Array<{id:string;cert_name:string}>;bookings?:Row[]};
const TABS=[
  {key:"overview",label:"Overview",icon:LayoutDashboard}, {key:"listings",label:"Listings",icon:Wrench},
  {key:"claims",label:"Ownership claims",icon:ClipboardList},{key:"reviews",label:"Reviews & history",icon:Star},
  {key:"bookings",label:"Bookings",icon:BookOpen},{key:"users",label:"Accounts",icon:Users},{key:"policies",label:"Policies & reporting",icon:Shield},
] as const;

export function AdminWorkspace() {
  const params=useSearchParams(), router=useRouter();
  const oldTab=params.get("tab");
  const fallback=oldTab==="pending"||oldTab==="approved"?"listings":oldTab;
  const requested=params.get("view")||fallback||"overview";
  const view=(TABS.some(t=>t.key===requested)?requested:"overview") as AdminView;
  const page=Math.max(1,Number.parseInt(params.get("page")||"1",10)||1);
  const filter=params.get("filter")||(oldTab==="pending"?"pending":oldTab==="approved"?"published":"all");
  const query=params.get("q")||"";
  const [draft,setDraft]=useState(query),[data,setData]=useState<Data|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(""),[message,setMessage]=useState("");
  const [refresh,setRefresh]=useState(0),[busy,setBusy]=useState<string|null>(null),[detail,setDetail]=useState<Detail|null>(null),[detailLoading,setDetailLoading]=useState(false),[note,setNote]=useState("");
  const [actionDialog,setActionDialog]=useState<{row:Row;action:string}|null>(null),[credentialUrl,setCredentialUrl]=useState("");
  useEffect(()=>{setDraft(query);},[query]);
  useEffect(()=>{
    const abort=new AbortController();
    setLoading(true);setError("");
    const p=new URLSearchParams({view,page:String(page),filter,q:query});
    fetch(`/api/admin/workspace?${p}`,{signal:abort.signal,cache:"no-store"}).then(async res=>{
      const value=await res.json();
      if(!res.ok)throw new Error(value.error||"Admin workspace could not be loaded.");
      if(!abort.signal.aborted)setData(value);
    }).catch(err=>{if(!abort.signal.aborted){setData(null);setError(err.message);}}).finally(()=>{if(!abort.signal.aborted)setLoading(false);});
    return()=>abort.abort();
  },[view,page,filter,query,refresh]);

  function navigate(next:Partial<{view:string;filter:string;page:number;q:string}>) {
    const p=new URLSearchParams({view:next.view??view,filter:next.filter??filter,page:String(next.page??1),q:next.q??query});
    router.push(`/admin?${p}`); setMessage("");setActionDialog(null);setDetail(null);
  }
  async function act(row:Row,action:string,reason?:string) {
    setBusy(row.id);setError("");setMessage("");
    try{
      const res=await fetch("/api/admin/actions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,id:row.id,expected_updated_at:row.updated_at,reason,source_url:action==="record_credential"?credentialUrl:undefined,credential_number:row.pirb_number||undefined})});
      const body=await res.json();if(!res.ok)throw new Error(body.error||"Action failed.");
      setMessage(body.message);setActionDialog(null);setDetail(null);setRefresh(v=>v+1);
    }catch(err){setError(err instanceof Error?err.message:"Action could not be confirmed.");}
    finally{setBusy(null);}
  }
  async function openDetails(row:Row) {
    setDetailLoading(true);setError("");
    try{
      const res=await fetch(`/api/admin/plumber-detail?id=${encodeURIComponent(row.id)}`,{cache:"no-store"});const body=await res.json();if(!res.ok)throw new Error(body.error||"Details could not load.");setDetail(body);
    }catch(err){setError(err instanceof Error?err.message:"Details could not load.");}finally{setDetailLoading(false);}
  }
  function dialog(row:Row,action:string){setActionDialog({row,action});setNote("");setCredentialUrl(row.verification_source_url||"");}
  const filters=view==="listings"?["all","published","pending","unclaimed"]:view==="claims"?["all","pending","approved","rejected"]:view==="reviews"?["all","current","history"]:view==="bookings"?["all","pending","confirmed","cancelled"]:["all","plumber","homeowner","admin"];
  const total=data?.total??0, pages=Math.max(1,Math.ceil(total/(data?.pageSize||25)));

  return <div className="mx-auto max-w-7xl px-4 py-8 sm:px-6">
    <header className="mb-6 flex flex-wrap items-start justify-between gap-4">
      <div><p className="text-xs font-bold uppercase tracking-widest text-brand">KZN Plumbers · administration</p><h1 className="mt-2 text-3xl font-bold text-slate-950">Directory workspace</h1><p className="mt-2 text-sm text-slate-600">Manage published listings, ownership requests and review history without a new database setup.</p></div>
      <button className="btn-secondary" onClick={()=>setRefresh(v=>v+1)} disabled={loading}><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`} aria-hidden="true"/>Refresh</button>
    </header>
    <nav className="mb-6 flex gap-2 overflow-x-auto border-b border-slate-200 pb-4" aria-label="Administration sections">{TABS.map(t=><button key={t.key} onClick={()=>navigate({view:t.key,filter:"all",q:""})} aria-current={view===t.key?"page":undefined} className={`inline-flex shrink-0 items-center gap-2 rounded-lg px-3 py-2.5 text-sm font-semibold ${view===t.key?"bg-slate-950 text-white":"border border-slate-200 bg-white text-slate-700 hover:border-brand"}`}><t.icon className="h-4 w-4" aria-hidden="true"/>{t.label}</button>)}</nav>
    {message&&<p role="status" className="mb-5 rounded-xl border border-emerald-200 bg-emerald-50 p-4 text-sm text-emerald-900">{message}</p>}
    {error&&<p role="alert" className="mb-5 rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-900">{error} <button onClick={()=>setRefresh(v=>v+1)} className="ml-2 underline">Try refresh</button></p>}
    {loading?<div role="status" className="flex items-center gap-3 py-14 text-slate-600"><Loader2 className="h-5 w-5 animate-spin"/>Loading {view}…</div>:data&&<>
      {view==="overview"?<>
        <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
          <Stat label="Published business records" metric={data.published}/><Stat label="Unpublished records" metric={data.pending}/><Stat label="Pending ownership claims" metric={data.claims}/><Stat label="Pending bookings" metric={data.bookings}/><Stat label="Registered accounts" metric={data.users}/><Stat label="Stored first-party reviews" metric={data.reviews}/><Stat label="Contact clicks · 30 days" metric={{value:data.contacts30d??null,status:data.capabilities?.leadEvents||"not_configured"}}/>
        </div>
        <div className="mt-7 grid gap-5 md:grid-cols-2"><section className="panel"><h2 className="text-xl font-bold">Useful next actions</h2><div className="mt-4 flex flex-col items-start gap-3"><button className="text-brand font-semibold" onClick={()=>navigate({view:"claims",filter:"pending"})}>Review pending ownership claims →</button><button className="text-brand font-semibold" onClick={()=>navigate({view:"reviews",filter:"history"})}>Inspect older review submissions →</button><button className="text-brand font-semibold" onClick={()=>navigate({view:"policies",filter:"all"})}>Read database capability and policy observations →</button></div></section><section className="panel"><h2 className="text-xl font-bold">Code-first release</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">Publishing a business is not credential verification. Earlier review submissions remain stored. Features that need missing database columns are shown as unavailable instead of pretending to save.</p><Link href="/trust" className="mt-4 inline-block text-sm font-semibold text-brand">Read the public verification method →</Link></section></div>
      </>:view==="policies"?<>
        <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="flex items-center gap-2 text-lg font-bold text-amber-950"><AlertTriangle className="h-5 w-5"/>Database policies have not been changed</h2><p className="mt-2 text-sm leading-relaxed text-amber-900">{data.notice}</p></section>
        <section className="panel mt-5"><h2 className="text-xl font-bold">Capability report</h2><div className="mt-4 grid gap-3 sm:grid-cols-2">{Object.entries(data.capabilities||{}).map(([name,status])=><div key={name} className="rounded-lg border border-slate-200 p-3"><div className="text-sm font-semibold">{featureName(name)}</div><div className="mt-1 text-sm text-slate-600">{featureLabel(status)}</div></div>)}</div></section>
        <section className="panel mt-5"><h2 className="text-xl font-bold">Anonymous-access observations</h2><p className="mt-2 text-sm text-slate-500">Only record counts are inspected; account data and certificate links are not fetched by these probes.</p><div className="mt-4 space-y-3">{data.probes?.map(p=><div key={p.table} className={`rounded-lg border p-4 ${p.status==="attention"?"border-amber-300 bg-amber-50":"border-slate-200"}`}><h3 className="font-semibold">{p.table}</h3><p className="mt-1 text-sm text-slate-700">{p.message}</p><p className="mt-2 text-xs text-slate-500">Visible to an anonymous read: {p.visibleRows??"not checked"} · Total rows: {p.totalRows??"not checked"}</p></div>)}</div><p className="mt-4 text-sm">Certificate storage bucket: <strong>{data.certBucket||"unknown"}</strong></p><p className="mt-1 text-xs text-slate-500">Checked {displayDate(data.checkedAt)}</p></section>
        <section className="panel mt-5"><h2 className="text-xl font-bold">Policy definitions — optional read-only export</h2><p className="mt-2 text-sm leading-relaxed text-slate-600">This query is for a database administrator who wants a complete report. It is not required to publish the code-first release, and this dashboard does not execute it.</p><pre className="mt-4 overflow-x-auto rounded-lg bg-slate-950 p-4 text-xs leading-relaxed text-slate-100">{data.policySql}</pre><button className="btn-secondary mt-3" onClick={()=>navigator.clipboard.writeText(data.policySql||"").then(()=>setMessage("Read-only policy query copied."),()=>setError("Select and copy the query manually."))}><FileText className="h-4 w-4"/>Copy read-only query</button><ul className="mt-4 list-disc space-y-2 pl-5 text-sm text-slate-600">{data.limitations?.map(s=><li key={s}>{s}</li>)}</ul></section>
        <section className="panel mt-5"><h2 className="text-xl font-bold">Listing and review reports</h2><p className="mt-3 text-sm leading-relaxed text-slate-600">Public corrections and complaints use the contact form and are delivered to the configured admin email. There is no report-ticket table in the legacy database, so this workspace does not pretend an inbox or ticket history exists.</p><div className="mt-4 flex gap-3"><Link className="btn-secondary" href="/corrections">Corrections process</Link><Link className="btn-secondary" href="/complaints">Complaints process</Link></div></section>
      </>:<>
        {view==="reviews"&&<section className="mb-5 rounded-xl border border-blue-200 bg-blue-50 p-5"><h2 className="text-xl font-bold text-blue-950">Latest feedback, preserved history</h2><p className="mt-2 text-sm text-blue-900">{data.notice}</p><div className="mt-3 flex flex-wrap gap-5 text-sm font-semibold"><span>{data.counts?.current??"—"} current</span><span>{data.counts?.history??"—"} older submissions</span><span>{data.counts?.duplicateGroups??"—"} repeated account/business groups</span></div><div className="mt-4 flex flex-wrap gap-2"><a className="btn-secondary" href="/api/admin/review-export?scope=all"><ArrowDownToLine className="h-4 w-4"/>Export stored reviews</a><a className="btn-secondary" href="/api/admin/review-export?scope=history"><ArrowDownToLine className="h-4 w-4"/>Export earlier history</a></div><p className="mt-3 text-xs text-blue-900">Private exports are not full database backups. Downloads do not remove or physically archive reviews.</p></section>}
        <form onSubmit={e=>{e.preventDefault();navigate({q:draft,page:1});}} className="mb-5 flex flex-wrap gap-3">
          {view!=="claims"&&<label className="flex min-w-56 flex-1 items-center gap-2 rounded-lg border border-slate-300 bg-white px-3"><Search className="h-4 w-4 text-slate-400"/><span className="sr-only">Search {view}</span><input value={draft} maxLength={100} onChange={e=>setDraft(e.target.value)} className="w-full bg-transparent py-2.5 text-sm outline-none" placeholder={view==="reviews"?"Business, reviewer or review text":"Search by name"}/></label>}
          <select aria-label={`Filter ${view}`} className="input w-auto" value={filter} onChange={e=>navigate({filter:e.target.value})}>{filters.map(f=><option key={f} value={f}>{f.charAt(0).toUpperCase()+f.slice(1)}</option>)}</select>
          {view!=="claims"&&<button className="btn-primary" type="submit">Search</button>}
        </form>
        {data.items?.length?<div className="space-y-4">{data.items.map(row=><article key={row.id} className="rounded-xl border border-slate-200 bg-white p-5">
          {view==="listings"?<>
            <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold text-slate-950">{row.trading_name}</h2><p className="mt-1 text-sm text-slate-600">{row.area} · {row.is_verified?"Published":"Not published"} · {row.profile_id?"Account linked":"Unclaimed record"}</p><p className="mt-2 text-xs text-slate-500">Recorded PIRB number: {row.pirb_number||"not supplied"} · {row.certifications?.[0]?.count??0} evidence files · {row.photos?.[0]?.count??0} photos</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" disabled={busy===row.id||detailLoading} onClick={()=>void openDetails(row)}>Inspect details</button>{row.is_verified&&<Link href={`/plumber/${row.slug||row.id}`} className="btn-secondary">Public profile</Link>}<button className={row.is_verified?"btn-secondary":"btn-primary"} disabled={busy===row.id} onClick={()=>dialog(row,row.is_verified?"unpublish":"publish")}>{row.is_verified?"Unpublish":"Publish listing"}</button></div></div>
            <p className="mt-3 text-sm text-slate-600">{row.specialties?.join(" · ")||"No services supplied"}</p>
            {data.capabilities?.verification==="available"?<div className="mt-4 flex flex-wrap gap-3 border-t border-slate-100 pt-3"><span className="self-center text-xs text-slate-500">Credential state recorded: {row.verification_state||"unknown"}</span><button className="text-sm font-semibold text-brand" disabled={busy===row.id} onClick={()=>dialog(row,"record_credential")}>Record a credential check</button>{row.verification_state==="credential_verified"&&<button className="text-sm text-red-700" disabled={busy===row.id} onClick={()=>dialog(row,"clear_credential")}>Withdraw credential label</button>}</div>:<p className="mt-4 rounded-lg bg-slate-50 p-3 text-xs text-slate-600">Credential evidence fields are {featureLabel(data.capabilities?.verification)}. Publishing this listing will not award a credential-verified badge.</p>}
          </>:view==="claims"?<>
            <div className="flex flex-wrap items-start justify-between gap-4"><div><h2 className="text-lg font-bold">{businessOf(row)}</h2><p className="mt-1 text-sm text-slate-600">{row.claimant?.full_name||"Claimant"} · {row.claimant?.email||"Email unavailable"}</p><p className="mt-1 text-sm text-slate-600">Phone supplied: {row.phone_entered||"—"}</p></div><Badge>{row.status}</Badge></div><p className="mt-3 text-xs text-slate-500">Submitted {displayDate(row.created_at)}. Matching a public phone number is not proof of ownership.</p>{row.admin_notes&&<p className="mt-3 whitespace-pre-wrap text-sm text-slate-700">{row.admin_notes}</p>}{row.status==="pending"&&<div className="mt-4 flex gap-2"><button className="btn-primary" disabled={busy===row.id} onClick={()=>dialog(row,"approve_claim")}>Approve after evidence review</button><button className="btn-secondary" disabled={busy===row.id} onClick={()=>dialog(row,"reject_claim")}>Reject with reason</button></div>}
          </>:view==="reviews"?<>
            <div className="flex flex-wrap items-center justify-between gap-3"><h2 className="font-bold">{row.business}</h2><Badge>{row.history_state==="history"?"Earlier history — retained":row.history_state==="current"?"Current feedback":"Classification incomplete"}</Badge></div><p className="mt-2 text-sm text-slate-600">{row.reviewer_name||"Reviewer"} · {row.rating??"—"}/5 · {displayDate(row.created_at)}</p><p className="mt-3 whitespace-pre-wrap text-sm leading-relaxed text-slate-800">{row.comment||"No written comment"}</p><p className="mt-3 text-xs text-slate-400">Review reference: {row.id}</p>{row.slug&&<Link className="mt-3 inline-block text-sm font-semibold text-brand" href={`/plumber/${row.slug}`}>View business →</Link>}
          </>:view==="bookings"?<>
            <div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{row.customer_name} → {businessOf(row)}</h2><p className="mt-1 text-sm text-slate-600">{row.customer_phone} · Preferred {displayDate(row.preferred_datetime)}</p></div><Badge>{row.status}</Badge></div><p className="mt-3 whitespace-pre-wrap text-sm text-slate-800">{row.job_description}</p>{row.notes&&<p className="mt-3 whitespace-pre-wrap rounded-lg bg-slate-50 p-3 text-xs leading-relaxed text-slate-600">{row.notes}</p>}<div className="mt-4 flex gap-2">{row.status!=="confirmed"&&<button className="btn-primary" disabled={busy===row.id} onClick={()=>dialog(row,"confirm_booking")}>Confirm request</button>}{row.status!=="cancelled"&&<button className="btn-secondary" disabled={busy===row.id} onClick={()=>dialog(row,"cancel_booking")}>Cancel request</button>}</div>
          </>:<div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-bold">{row.full_name||"Account"}</h2><p className="mt-1 text-sm text-slate-600">{row.email}</p><p className="mt-2 text-xs text-slate-500">Joined {displayDate(row.created_at)} · {businessOf(row)}</p></div><Badge>{row.role}</Badge></div>}
        </article>)}</div>:<div className="panel py-12 text-center text-slate-500">No records in this view.</div>}
        <nav className="mt-7 flex items-center justify-between gap-4" aria-label="Admin records pagination"><button className="btn-secondary" disabled={page<=1} onClick={()=>navigate({page:page-1})}><ArrowLeft className="h-4 w-4"/>Previous</button><span className="text-sm text-slate-600">Page {page} of {pages} · {total.toLocaleString()} records</span><button className="btn-secondary" disabled={page>=pages} onClick={()=>navigate({page:page+1})}>Next<ArrowRight className="h-4 w-4"/></button></nav>
      </>}
    </>}
    {actionDialog&&<div className="fixed inset-0 z-[80] flex items-center justify-center overflow-y-auto bg-slate-950/65 p-4" role="dialog" aria-modal="true" aria-labelledby="admin-confirm-title"><section className="my-auto w-full max-w-lg rounded-2xl bg-white p-6 shadow-xl"><h2 id="admin-confirm-title" className="text-xl font-bold">Confirm {actionDialog.action.replace(/_/g," ")}</h2><p className="mt-3 text-sm text-slate-600">{actionDialog.row.trading_name||businessOf(actionDialog.row)}. This is a real change to the connected database, not a test.</p>{actionDialog.action==="unpublish"&&<p className="mt-2 text-sm text-slate-600">The business record is kept, but its public listing is hidden.</p>}{actionDialog.action==="publish"&&<p className="mt-2 text-sm text-slate-600">This approves publication only. It does not certify the business.</p>}{["approve_claim","reject_claim","record_credential"].includes(actionDialog.action)&&<label className="mt-4 block text-sm font-semibold">Evidence reviewed / reason<textarea value={note} onChange={e=>setNote(e.target.value)} className="input mt-2" maxLength={1000} rows={4}/></label>}{actionDialog.action==="record_credential"&&<label className="mt-4 block text-sm font-semibold">Authoritative evidence URL<input type="url" value={credentialUrl} onChange={e=>setCredentialUrl(e.target.value)} className="input mt-2" placeholder="https://"/><span className="mt-2 block text-xs font-normal text-slate-500">For recorded registration number {actionDialog.row.pirb_number||"not supplied"}. Use the source you actually checked.</span></label>}{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-6 flex justify-end gap-3"><button className="btn-secondary" disabled={!!busy} onClick={()=>setActionDialog(null)}>Cancel</button><button className="btn-primary" disabled={!!busy||(["approve_claim","reject_claim","record_credential"].includes(actionDialog.action)&&note.trim().length<10)} onClick={()=>void act(actionDialog.row,actionDialog.action,note)}>{busy?"Saving…":"Confirm and save"}</button></div></section></div>}
    {detail&&<div className="fixed inset-0 z-[80] overflow-y-auto bg-slate-950/65 p-4" role="dialog" aria-modal="true" aria-labelledby="admin-detail-title"><section className="mx-auto my-8 max-w-2xl rounded-2xl bg-white p-6 shadow-xl"><div className="flex items-start justify-between gap-3"><h2 id="admin-detail-title" className="text-xl font-bold">{detail.plumber?.trading_name}</h2><button aria-label="Close business details" className="btn-secondary" onClick={()=>setDetail(null)}><X className="h-4 w-4"/></button></div><p className="mt-3 text-sm text-slate-600">{detail.plumber?.area} · {detail.plumber?.is_verified?"Published":"Unpublished"}</p><h3 className="mt-6 font-bold">Credential evidence</h3><p className="mt-2 text-xs text-slate-500">Open only if needed for review. New links are temporary and access-checked.</p><div className="mt-3 space-y-2">{detail.certifications?.length?detail.certifications.map(c=><a key={c.id} href={`/api/certifications/${c.id}`} target="_blank" rel="noopener noreferrer" className="flex items-center gap-2 rounded-lg border border-slate-200 p-3 text-sm font-semibold text-brand"><FileText className="h-4 w-4"/>{c.cert_name}</a>):<p className="text-sm text-slate-500">No evidence files are attached.</p>}</div><h3 className="mt-6 font-bold">Recent bookings</h3>{detail.bookings?.length?detail.bookings.map(b=><p key={b.id} className="mt-2 border-b border-slate-100 pb-2 text-sm">{b.customer_name}: {b.job_description} · {b.status}</p>):<p className="mt-2 text-sm text-slate-500">No recent bookings.</p>}</section></div>}
  </div>;
}

function businessOf(row:Row){const p=Array.isArray(row.plumber)?row.plumber[0]:row.plumber;return p?.trading_name||"No linked business";}
function displayDate(value?:string){if(!value)return"—";const d=new Date(value);return Number.isNaN(d.getTime())?"Unknown date":d.toLocaleString("en-ZA",{timeZone:"Africa/Johannesburg",dateStyle:"medium",timeStyle:"short"});}
function featureName(value:string){return ({verification:"Credential evidence fields",leadEvents:"Lead-event storage",bookingOutcomes:"Structured job outcomes",listingStatus:"Detailed publication status"} as Record<string,string>)[value]||value;}
function featureLabel(value?:string){return value==="available"?"Available":value==="not_configured"?"Not installed — legacy mode":"Could not verify";}
function Stat({label,metric}:{label:string;metric?:Metric}){return<section className="rounded-xl border border-slate-200 bg-white p-5"><div className="text-3xl font-bold text-slate-950">{metric?.value===null||metric?.value===undefined?"—":metric.value.toLocaleString()}</div><h2 className="mt-2 text-sm font-semibold text-slate-700">{label}</h2>{metric?.value===null&&<p className="mt-2 text-xs text-slate-500">{featureLabel(metric.status)}</p>}</section>;}
function Badge({children}:{children:React.ReactNode}){return<span className="inline-flex self-start rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-700">{children||"Unknown"}</span>;}
